version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
    - 5.1.0
    - 5.1.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.22
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: jest
    versions:
    - 25.5.4
    - 26.6.3
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: ts-jest
    versions:
    - 25.5.1
